//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Driverslog {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Driverslog.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical support.
        /// </summary>
        public static string AboutTechSupport {
            get {
                return ResourceManager.GetString("AboutTechSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutViewTitle {
            get {
                return ResourceManager.GetString("AboutViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRIVER&apos;S LOG.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new expense.
        /// </summary>
        public static string CreateExpenseViewTitle {
            get {
                return ResourceManager.GetString("CreateExpenseViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new trip.
        /// </summary>
        public static string CreateViewTitle {
            get {
                return ResourceManager.GetString("CreateViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really wan&apos;t to delete this expense?.
        /// </summary>
        public static string EditExpenseDeleteConfirm {
            get {
                return ResourceManager.GetString("EditExpenseDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expense.
        /// </summary>
        public static string EditExpenseViewTitle {
            get {
                return ResourceManager.GetString("EditExpenseViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really wan&apos;t to delete this trip?.
        /// </summary>
        public static string EditTripDeleteConfirm {
            get {
                return ResourceManager.GetString("EditTripDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trip.
        /// </summary>
        public static string EditViewTitle {
            get {
                return ResourceManager.GetString("EditViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string ExpenseAmount {
            get {
                return ResourceManager.GetString("ExpenseAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        public static string ExpenseCar {
            get {
                return ResourceManager.GetString("ExpenseCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string ExpenseDate {
            get {
                return ResourceManager.GetString("ExpenseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string ExpenseDelete {
            get {
                return ResourceManager.GetString("ExpenseDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string ExpenseNotes {
            get {
                return ResourceManager.GetString("ExpenseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string ExpenseSave {
            get {
                return ResourceManager.GetString("ExpenseSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string ExpenseTitle {
            get {
                return ResourceManager.GetString("ExpenseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a title of the expense.
        /// </summary>
        public static string ExpenseValidateTitleEmpty {
            get {
                return ResourceManager.GetString("ExpenseValidateTitleEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        public static string MainPageAll {
            get {
                return ResourceManager.GetString("MainPageAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear.
        /// </summary>
        public static string MainPageAppBarClear {
            get {
                return ResourceManager.GetString("MainPageAppBarClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expense.
        /// </summary>
        public static string MainPageAppBarExpense {
            get {
                return ResourceManager.GetString("MainPageAppBarExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to export.
        /// </summary>
        public static string MainPageAppBarExport {
            get {
                return ResourceManager.GetString("MainPageAppBarExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string MainPageAppBarSettings {
            get {
                return ResourceManager.GetString("MainPageAppBarSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trip.
        /// </summary>
        public static string MainPageAppBarTrip {
            get {
                return ResourceManager.GetString("MainPageAppBarTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All trips and expenses will be deleted. Make sure you&apos;ve exported them..
        /// </summary>
        public static string MainPageClearConfirm {
            get {
                return ResourceManager.GetString("MainPageClearConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expenses.
        /// </summary>
        public static string MainPageExpenses {
            get {
                return ResourceManager.GetString("MainPageExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        public static string MainPageToday {
            get {
                return ResourceManager.GetString("MainPageToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trips.
        /// </summary>
        public static string MainPageTrips {
            get {
                return ResourceManager.GetString("MainPageTrips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string MessageBoxConfirm {
            get {
                return ResourceManager.GetString("MessageBoxConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default car.
        /// </summary>
        public static string SettingsDefaultCar {
            get {
                return ResourceManager.GetString("SettingsDefaultCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default export to e-mail.
        /// </summary>
        public static string SettingsDefaultExportToEmail {
            get {
                return ResourceManager.GetString("SettingsDefaultExportToEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance unit.
        /// </summary>
        public static string SettingsDistanceUnit {
            get {
                return ResourceManager.GetString("SettingsDistanceUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide mileage field.
        /// </summary>
        public static string SettingsHideMileageField {
            get {
                return ResourceManager.GetString("SettingsHideMileageField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide odometer fields.
        /// </summary>
        public static string SettingsHideOdometerFields {
            get {
                return ResourceManager.GetString("SettingsHideOdometerFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string SettingsSave {
            get {
                return ResourceManager.GetString("SettingsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsViewTitle {
            get {
                return ResourceManager.GetString("SettingsViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve reached the trial limit.
        ///Your log can contain {0} items in this trial version.
        ///Select OK in order to buy the full version of Driver&apos;s log..
        /// </summary>
        public static string TrialLimitReachedMessage {
            get {
                return ResourceManager.GetString("TrialLimitReachedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial limit reached.
        /// </summary>
        public static string TrialLimitReachedTitle {
            get {
                return ResourceManager.GetString("TrialLimitReachedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        public static string TripCar {
            get {
                return ResourceManager.GetString("TripCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string TripDate {
            get {
                return ResourceManager.GetString("TripDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string TripDelete {
            get {
                return ResourceManager.GetString("TripDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string TripFrom {
            get {
                return ResourceManager.GetString("TripFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mileage.
        /// </summary>
        public static string TripMileage {
            get {
                return ResourceManager.GetString("TripMileage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string TripNotes {
            get {
                return ResourceManager.GetString("TripNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odometer Start.
        /// </summary>
        public static string TripOdometerStart {
            get {
                return ResourceManager.GetString("TripOdometerStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odometer Stop.
        /// </summary>
        public static string TripOdometerStop {
            get {
                return ResourceManager.GetString("TripOdometerStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round Trip.
        /// </summary>
        public static string TripRoundTrip {
            get {
                return ResourceManager.GetString("TripRoundTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string TripSave {
            get {
                return ResourceManager.GetString("TripSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string TripTo {
            get {
                return ResourceManager.GetString("TripTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown distance.
        /// </summary>
        public static string TripUnknownDistance {
            get {
                return ResourceManager.GetString("TripUnknownDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify where you&apos;re traveling from.
        /// </summary>
        public static string TripValidateFromEmpty {
            get {
                return ResourceManager.GetString("TripValidateFromEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
