//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Driverslog {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Driverslog.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRIVER&apos;S LOG.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new trip.
        /// </summary>
        public static string CreateViewTitle {
            get {
                return ResourceManager.GetString("CreateViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        public static string MainPageAll {
            get {
                return ResourceManager.GetString("MainPageAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear.
        /// </summary>
        public static string MainPageAppBarClear {
            get {
                return ResourceManager.GetString("MainPageAppBarClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expense.
        /// </summary>
        public static string MainPageAppBarExpense {
            get {
                return ResourceManager.GetString("MainPageAppBarExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to export.
        /// </summary>
        public static string MainPageAppBarExport {
            get {
                return ResourceManager.GetString("MainPageAppBarExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string MainPageAppBarSettings {
            get {
                return ResourceManager.GetString("MainPageAppBarSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trip.
        /// </summary>
        public static string MainPageAppBarTrip {
            get {
                return ResourceManager.GetString("MainPageAppBarTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All trips and expenses will be deleted. Make sure you&apos;ve exported them..
        /// </summary>
        public static string MainPageClearConfirm {
            get {
                return ResourceManager.GetString("MainPageClearConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expenses.
        /// </summary>
        public static string MainPageExpenses {
            get {
                return ResourceManager.GetString("MainPageExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        public static string MainPageToday {
            get {
                return ResourceManager.GetString("MainPageToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trips.
        /// </summary>
        public static string MainPageTrips {
            get {
                return ResourceManager.GetString("MainPageTrips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string MessageBoxConfirm {
            get {
                return ResourceManager.GetString("MessageBoxConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        public static string TripCar {
            get {
                return ResourceManager.GetString("TripCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string TripDate {
            get {
                return ResourceManager.GetString("TripDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string TripFrom {
            get {
                return ResourceManager.GetString("TripFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mileage.
        /// </summary>
        public static string TripMileage {
            get {
                return ResourceManager.GetString("TripMileage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string TripNotes {
            get {
                return ResourceManager.GetString("TripNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odometer Start.
        /// </summary>
        public static string TripOdometerStart {
            get {
                return ResourceManager.GetString("TripOdometerStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odometer Stop.
        /// </summary>
        public static string TripOdometerStop {
            get {
                return ResourceManager.GetString("TripOdometerStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round Trip.
        /// </summary>
        public static string TripRoundTrip {
            get {
                return ResourceManager.GetString("TripRoundTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string TripSave {
            get {
                return ResourceManager.GetString("TripSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string TripTo {
            get {
                return ResourceManager.GetString("TripTo", resourceCulture);
            }
        }
    }
}
